export const INTERFACE_ACTIONS = {
    SYNTH_ONE_PARAMS: 'SYNTH_ONE_PARAMS',
    SYNTH_TWO_PARAMS: 'SYNTH_TWO_PARAMS',
    INTERFACE_MASTER_PARAMS: 'INTERFACE_MASTER_PARAMS',
    FETCH_ALL_SYNTH_PARAMS: 'GET_ALL_SYNTH_PARAMS'
}